TRUNCATE TABLE candidat CASCADE;
TRUNCATE TABLE disponibilite CASCADE;
TRUNCATE TABLE disponibilite_places CASCADE;
TRUNCATE TABLE etablissement CASCADE;
TRUNCATE TABLE experience CASCADE;
TRUNCATE TABLE opinion CASCADE;
TRUNCATE TABLE reference CASCADE;